"""Stable public contracts for the additive FireViewer MVP."""

from fireviewer_contracts.mvp.contracts.common import (
    CandidateArea,
    CandidateCluster,
    LocationCandidate,
    ProviderRun,
    ScoreBreakdown,
    TimeWindow,
)
from fireviewer_contracts.mvp.contracts.detection_v1 import Detection, DetectionResultV1
from fireviewer_contracts.mvp.contracts.event_evidence_v1 import (
    Claim,
    Contradiction,
    EventEvidenceV1,
    EvidenceMedia,
    EvidenceSource,
    SatelliteObservation,
    Uncertainty,
    VisualObservation,
)
from fireviewer_contracts.mvp.contracts.geographic_hypothesis_v1 import (
    GeographicAbstention,
    GeographicHypothesis,
    GeographicHypothesisResultV1,
    GeographicReference,
    GeographicScoreBreakdown,
)
from fireviewer_contracts.mvp.contracts.localization_v1 import (
    CameraEvidence,
    CameraGroup,
    CameraIntrinsics,
    CameraPose,
    LocalizationResultV1,
    PoseUncertainty,
    RayUncertainty,
    TargetRay,
)
from fireviewer_contracts.mvp.contracts.point_supervision_v1 import (
    AUTO_PUBLICATION_CONFIDENCE_THRESHOLD,
    AssessmentSubscores,
    CandidatePoint,
    CompetingPointJsonV1,
    GeospatialConsistencyCheck,
    PointAssessmentV1,
    PointEvidenceBundleV1,
    PointEvidenceReference,
    PriorFireStateReference,
    RagContextExcerpt,
    UploadLocationEvidence,
)
from fireviewer_contracts.mvp.contracts.satellite_v1 import (
    SatelliteMask,
    SatelliteResultV1,
    SatelliteScene,
)

__all__ = [
    "AUTO_PUBLICATION_CONFIDENCE_THRESHOLD",
    "AssessmentSubscores",
    "CameraEvidence",
    "CameraGroup",
    "CameraIntrinsics",
    "CameraPose",
    "CandidateArea",
    "CandidateCluster",
    "CandidatePoint",
    "Claim",
    "CompetingPointJsonV1",
    "Contradiction",
    "Detection",
    "DetectionResultV1",
    "EventEvidenceV1",
    "EvidenceMedia",
    "EvidenceSource",
    "GeographicAbstention",
    "GeographicHypothesis",
    "GeographicHypothesisResultV1",
    "GeographicReference",
    "GeographicScoreBreakdown",
    "GeospatialConsistencyCheck",
    "LocalizationResultV1",
    "LocationCandidate",
    "PointAssessmentV1",
    "PointEvidenceBundleV1",
    "PointEvidenceReference",
    "PoseUncertainty",
    "PriorFireStateReference",
    "ProviderRun",
    "RagContextExcerpt",
    "RayUncertainty",
    "SatelliteMask",
    "SatelliteObservation",
    "SatelliteResultV1",
    "SatelliteScene",
    "ScoreBreakdown",
    "TargetRay",
    "TimeWindow",
    "Uncertainty",
    "UploadLocationEvidence",
    "VisualObservation",
]
